### ISSUE TITLE
Enhance Project Structure Following Python Best Practices

### ISSUE THREAD

**Issue by e-florez** [e-florez/radial_distribution#11]
## Current Status
The project currently lacks a standardized Python package structure, which may affect maintainability and ease of installation.

### 1. Implement Standard Python Package Structure
```
pyCC/
├── .github/
│   └── workflows/
├── docs/
│   ├── conf.py
│   ├── index.rst
│   └── api.rst
├── src/
│   └── pycc/
│       ├── __init__.py
│       ├── core/
│       │   ├── __init__.py
│       │   ├── cluster.py
│       │   └── compare.py
│       ├── utils/
│       │   ├── __init__.py
│       │   └── helpers.py
│       └── visualization/
│           ├── __init__.py
│           └── plots.py
├── tests/
│   ├── __init__.py
│   ├── test_cluster.py
│   └── test_compare.py
├── examples/
│   ├── basic_usage.py
│   └── advanced_comparisons.py
├── .gitignore
├── LICENSE
├── MANIFEST.in
├── pyproject.toml
├── README.md
└── tox.ini
```

### 2. Required Files
- Add `pyproject.toml` for modern Python packaging
- Create proper `__init__.py` files with version info
- Include `MANIFEST.in` for package data
- Add `tox.ini` for testing multiple Python versions

### 3. Dependencies Management
```toml
# pyproject.toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pycc"
version = "0.1.0"
authors = [
    { name = "Your Name", email = "your.email@example.com" },
]
description = "Cluster Compare: A tool for analyzing atomic and molecular clusters"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.20",
    "scipy>=1.7",
    "pandas>=1.3",
    "matplotlib>=3.4",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-cov>=3.0",
    "black>=22.0",
    "isort>=5.0",
    "flake8>=4.0",
]
```

## Benefits
1. Easier installation via pip
2. Clear separation of concerns
3. Better testing infrastructure
4. Simplified dependency management
5. Improved developer experience

## Implementation Steps
1. Create new directory structure
2. Move existing code to appropriate locations
3. Add necessary package files
4. Update import statements
5. Create basic documentation structure
6. Set up testing framework

## Questions
- Should we maintain backward compatibility?
- What should be the minimum supported Python version?
- Do we need to support any specific operating systems?

## Additional Notes
- This restructuring will make the package pip-installable
- Will facilitate future additions of new features
- Makes it easier for new contributors to understand the codebase

Labels: enhancement, good first issue, help wanted, infrastructure

---

### Phase 1: Basic Structure Setup
- [x] Create new directory structure
- [x] Add `.gitignore` with Python-specific entries
- [ ] Set up initial `pyproject.toml`
- [x] Create empty `__init__.py` files
- [x] Move existing code to `src/pycc/` directory

### Phase 2: Code Organization
- [ ] Organize code into core modules:
  - [ ] Move cluster-related code to `core/cluster.py`
  - [ ] Move comparison functions to `core/compare.py`
  - [ ] Create utilities module in `utils/helpers.py`
  - [ ] Set up visualization module in `visualization/plots.py`
- [ ] Update import statements throughout the codebase
- [ ] Add version information to main `__init__.py`
- [ ] Create proper package exports

### Phase 3: Documentation Structure
- [ ] Set up Sphinx documentation:
  - [ ] Create docs/ directory
  - [ ] Initialize Sphinx configuration
  - [ ] Add basic API documentation structure
  - [ ] Include examples directory
- [ ] Update README.md with new structure information
- [ ] Add CONTRIBUTING.md guidelines
- [ ] Add CHANGELOG.md

### Phase 4: Testing Infrastructure
- [x] Set up pytest configuration
- [ ] Create basic test structure:
  - [ ] Add test_cluster.py
  - [ ] Add test_compare.py
  - [ ] Add test_helpers.py
- [ ] Add test data in tests/data/
- [ ] Configure coverage reporting

### Phase 5: CI/CD Setup
- [x] Create GitHub Actions workflow:
  - [x] Add Python package workflow
  - [x] Configure test automation
  - [x] Set up linting checks
  - [x] Configure documentation building
- [ ] Add status badges to README

### Phase 6: Package Management
- [ ] Complete `pyproject.toml` configuration
- [ ] Create `MANIFEST.in`
- [ ] Set up tox configuration
- [ ] Create development requirements
- [ ] Test package installation

### Phase 7: Quality Assurance
- [ ] Add pre-commit hooks:
  - [ ] black for code formatting
  - [ ] isort for import sorting
  - [ ] flake8 for linting
- [ ] Add type hints to core functions
- [ ] Run initial code quality checks
- [ ] Fix any identified issues

## Progress Tracking
- [ ] Phase 1 completed
- [ ] Phase 2 completed
- [ ] Phase 3 completed
- [ ] Phase 4 completed
- [ ] Phase 5 completed
- [ ] Phase 6 completed
- [ ] Phase 7 completed

## Definition of Done
- All checkboxes are marked
- Documentation is updated
- Tests are passing
- CI/CD pipeline is functional
- Package can be installed via pip
- Code quality checks pass
- At least one review approval
